[target.x86_64-unknown-linux-musl]
rustflags = [
  # Use the clang executable as the final linker driver, replacing the default C compiler (cc/gcc).
  "-C", "linker=clang-16", 
  # This is a linker argument passed through the driver (clang) to specify that it should use the LLD linker instead of its default (like GNU ld).
  # https://lld.llvm.org/#using-lld
  "-C", "link-arg=-fuse-ld=lld",
  # Force to use dynamic linker
  # https://doc.rust-lang.org/beta/reference/linkage.html#r-link.crt.crt-static
  "-C", "target-feature=-crt-static"
]

