# [language-server.rust-analyzer.config.check]
# command = "clippy"

[language-server.rust-analyzer.config.cargo]
features = "all"

[[language]]
name = "python"
language-servers = ["pylsp"]

[[language]]
name = "c"
indent = { "tab-width" = 4, unit = " " }
file-types = ["c", "h"]

